//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_kooil_testEntities : DbContext
    {
        public DB_kooil_testEntities()
            : base("name=DB_kooil_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_IGNELER> TBL_IGNELER { get; set; }
        public virtual DbSet<TBL_PERSONEL> TBL_PERSONEL { get; set; }
        public virtual DbSet<TBL_SIPARIS> TBL_SIPARIS { get; set; }
        public virtual DbSet<TBL_STOK> TBL_STOK { get; set; }
        public virtual DbSet<TBL_KANALACMA> TBL_KANALACMA { get; set; }
        public virtual DbSet<TBL_KONTROL> TBL_KONTROL { get; set; }
        public virtual DbSet<TBL_PRES> TBL_PRES { get; set; }
    }
}
