//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KANALACMA
    {
        public int SIPARISID { get; set; }
        public string IGNEKODU { get; set; }
        public Nullable<int> ISLENENMIKTAR { get; set; }
        public string RAPORLAYAN { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string NOT { get; set; }
    }
}
