//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HAMRAPOR
    {
        public int RAPORID { get; set; }
        public Nullable<int> SIPARISNO { get; set; }
        public string MUSTERI { get; set; }
        public string URUNTIPI { get; set; }
        public string URUNKODU { get; set; }
        public Nullable<int> PRESSAYI { get; set; }
        public Nullable<int> HAMHARCANAN { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> HAMKALINLIK { get; set; }
        public Nullable<decimal> HAMGENISLIK { get; set; }
        public string OZELLIK { get; set; }
        public string MENSEI { get; set; }
        public string RAPORLAYAN { get; set; }
        public Nullable<int> PARTINO { get; set; }
    }
}
