//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STOK
    {
        public int IGNEKOD { get; set; }
        public string IGNEADI { get; set; }
        public Nullable<int> STOKADET { get; set; }
    }
}
