//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_IADE
    {
        public int ID { get; set; }
        public string URUNKOD { get; set; }
        public Nullable<int> ADET { get; set; }
        public string FIRMA { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string RAPORLAYAN { get; set; }
        public Nullable<int> SIPNO { get; set; }
        public string NEDEN { get; set; }
        public string SONUC { get; set; }
        public string URUNTUR { get; set; }
        public string BARKOD { get; set; }
    }
}
