//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERS
    {
        public int ID { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<bool> anasayfa { get; set; }
        public Nullable<bool> yeniSiparis { get; set; }
        public Nullable<bool> akfifSiparis { get; set; }
        public Nullable<bool> siparisDurumKontrol { get; set; }
        public Nullable<bool> tamamlananSiparis { get; set; }
        public Nullable<bool> islemRaporlari { get; set; }
        public Nullable<bool> urunTurleri { get; set; }
        public Nullable<bool> yeniUrunEkle { get; set; }
        public Nullable<bool> urunDuzenle { get; set; }
        public Nullable<bool> urunStok { get; set; }
        public Nullable<bool> hamStok { get; set; }
        public Nullable<bool> yeniHam { get; set; }
        public Nullable<bool> hamSil { get; set; }
        public Nullable<bool> hamStokGuncelle { get; set; }
        public Nullable<bool> hamRapor { get; set; }
        public Nullable<bool> hamRaporEkle { get; set; }
        public Nullable<bool> firmalar { get; set; }
        public Nullable<bool> firmaEkle { get; set; }
        public Nullable<bool> yeniPSevkiyat { get; set; }
        public Nullable<bool> yeniSipSevkiyat { get; set; }
        public Nullable<bool> gecmisSevkiyat { get; set; }
        public Nullable<bool> pres { get; set; }
        public Nullable<bool> arkaSiyir { get; set; }
        public Nullable<bool> yolKopyala { get; set; }
        public Nullable<bool> ucSiyirma { get; set; }
        public Nullable<bool> kanalAcma { get; set; }
        public Nullable<bool> kanalBuyut { get; set; }
        public Nullable<bool> polisaj1 { get; set; }
        public Nullable<bool> dilCakma { get; set; }
        public Nullable<bool> polisaj2 { get; set; }
        public Nullable<bool> isilIslem { get; set; }
        public Nullable<bool> temper { get; set; }
        public Nullable<bool> yikama { get; set; }
        public Nullable<bool> bileme { get; set; }
        public Nullable<bool> kontrol { get; set; }
        public Nullable<bool> ayarlar { get; set; }
        public Nullable<bool> hataduzelt { get; set; }
        public Nullable<bool> iade { get; set; }
    }
}
