//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_URUNSTOKLOG
    {
        public int ID { get; set; }
        public string ISLEM { get; set; }
        public string URUN { get; set; }
        public Nullable<int> MIKTAR { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string RAPORLAYAN { get; set; }
    }
}
