//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HAMLOG
    {
        public int RAPORID { get; set; }
        public Nullable<decimal> KALINLIK { get; set; }
        public Nullable<decimal> GENISLIK { get; set; }
        public string OZELLIK { get; set; }
        public string MENSEI { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string ISLEM { get; set; }
        public string SEBEP { get; set; }
        public string RAPORLAYAN { get; set; }
        public Nullable<int> MIKTAR { get; set; }
    }
}
