//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FIRMALAR
    {
        public int ID { get; set; }
        public string FIRMAAD { get; set; }
        public string FIRMATAMAD { get; set; }
        public string VERGINO { get; set; }
        public string ADRES { get; set; }
        public string TELEFON1 { get; set; }
        public string TELEFON2 { get; set; }
        public string KONUM { get; set; }
        public string MAIL { get; set; }
        public string YETKILI { get; set; }
        public string VERGIDAIRESI { get; set; }
    }
}
