//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_kooil.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HAMMADDE
    {
        public int ID { get; set; }
        public Nullable<decimal> KALINLIK { get; set; }
        public Nullable<decimal> GENISLIK { get; set; }
        public string OZELLIK { get; set; }
        public string MENSEI { get; set; }
        public Nullable<int> MIKTAR { get; set; }
        public string KONUM { get; set; }
        public Nullable<bool> AKTIF { get; set; }
    }
}
